# Nome da Imagem a ser baixada
FROM node:23.5.0-slim

# Exeultando o comando de instalação do nodemon
RUN apt update && \
    npm install -g nodemon

COPY start.sh /
RUN chmod +x /start.sh

# Instanciado o usuário node
USER node

# Diretorio de trabalho
WORKDIR /home/node/app

# Copiando os arquivos package.json e package-lock.json
#COPY package*.json .
#COPY --chown=node:node package.json package-lock.json ./

# Instalando as dependências
#RUN npm install

# Expondo a porta 3000
EXPOSE 3000

# Executando o comando de inicialização
#CMD ["tail", "-f", "/dev/null"]

CMD ["/start.sh"] 